#!/bin/sh

# downloading NOA data now done in /etc/cron.daily/deq-drought-model (due to raster2pgsql trouble on deq1)
# Process Scripts in Drupal Root
#cd /var/www/html/d.dh
# retrieve precip to date
#drush scr modules/dh_weather/src/php/noaa_daily_precip_retrieval.php --date=today --single=FALSE
#rm /tmp/nws_precip_*
#rm /tmp/tmp_precipgrid.sql


# legacy code no longer used as of 8/31/2017
#cd /var/www/html/drought
#./daily.sh
# manual preip retrieval for new system
#/usr/bin/php vahydro-daily_precip_retrieval.php today FALSE FALSE 
# store updated precip summaries in VAHydro
#cd /var/www/html/d.dh

# Run R USGS Retrieval Scripts - gets SW and GW 7-day avg, cals %ile, then updates regions via REST
cd /var/www/R
sudo -u www-data Rscript drought/USGS_drought_flow.R
sudo -u www-data Rscript drought/USGS_drought_gwl.R
sudo -u www-data Rscript drought/USGS_monthly_frequency_plot_gen.R

#cd /var/www/html/drought
#cd ./state
#./daily.sh

# Manually trigger feeds importer (cron is busted?) of precip summary
# drush scr modules/dh_drought/src/import.dmtf.php
# New Method because cert does not work

# this section was commented out 10.18.22, beginning of water year. Un-comment in December
# Download the file 
cd /var/www/html/drought/state/images/maps
wget -O va-dmtf-precip --no-check-certificate  https://localhost/d.dh/va-dmtf-precip
cd /var/www/html/d.dh
drush scr modules/om/src/om_setprop.php file /var/www/html/drought/state/images/maps/va-dmtf-precip

# Create a static version of the map for each day.
cd /var/www/html/drought/state/images/maps
# wget -O virginia_drought.png "https://localhost/cgi-bin/mapserv?map=/var/www/html/mapserv/vahydro_drought_status-4-metrics-live.map&layers=poli_bounds&layers=proj_seggroups&mode=map&format=image/png" --no-check-certificate
wget -O virginia_drought.png "https://localhost/cgi-bin/mapserv?map=/var/www/html/mapserv/vahydro_drought_status-4-metrics-live.map&layers=poli_bounds&layers=proj_seggroups" --no-check-certificate
newmap=`ls -rt /var/www/html/drought/state/images/maps/ | grep imageMapFile | tail -n 1`
mv /var/www/html/drought/state/images/maps/${newmap} /var/www/html/drought/state/images/maps/virginia_drought.png

# Create a static version of the next-gen R indicators map for each day.
cd /var/www/R
sudo -u www-data Rscript drought/summary_map/virginia_drought_indicators_map.R

date > /home/denton/mydate
mail -s "DEQ1 drought.sh ran" denton@vt.edu < /home/denton/mydate

echo "4 of 9 deq-drought" >> /media/NAS/deq1daily.log
date >> /media/NAS/deq1daily.log

