#!/bin/sh
/opt/model/apache/maintenance/clean_debug.sh

date > /home/denton/mydate
mail -s "DEQ1 model_maintenance.sh run" denton@vt.edu < /home/denton/mydate

echo "7 of 9 deq-model-maintenance" >> /media/NAS/deq1daily.log
date >> /media/NAS/deq1daily.log

