#!/bin/sh

# Process Scripts in Drupal Root
cd /var/www/html/d.dh
# retrieve precip to date
drush scr modules/dh_weather/src/php/noaa_daily_precip_retrieval.php --date=today --single=FALSE


# legacy code no longer used as of 8/31/2017
#cd /var/www/html/drought
#./daily.sh
# manual preip retrieval for new system
#/usr/bin/php vahydro-daily_precip_retrieval.php today FALSE FALSE 
# store updated precip summaries in VAHydro
#cd /var/www/html/d.dh

# Run R USGS Retrieval Scripts - gets SW and GW 7-day avg, cals %ile, then updates regions via REST
cd /var/www/R
sudo -u www-data Rscript drought/USGS_drought_flow.R
sudo -u www-data Rscript drought/USGS_drought_gwl.R

#cd /var/www/html/drought
#cd ./state
#./daily.sh

# Manually trigger feeds importer (cron is busted?) of precip summary
# drush scr modules/dh_drought/src/import.dmtf.php
# New Method because cert does not work
# Download the file 
cd /var/www/html/drought/state/images/maps
wget -O va-dmtf-precip --no-check-certificate  https://localhost/d.dh/va-dmtf-precip
cd /var/www/html/d.dh
drush scr modules/om/src/om_setprop.php file /var/www/html/drought/state/images/maps/va-dmtf-precip
# Create a static version of the map for each day.
wget -O virginia_drought.png "https://localhost/cgi-bin/mapserv?map=/var/www/html/mapserv/vahydro_drought_status-4-metrics-live.map&layers=usgs_mllr&layers=poli_bounds&layers=proj_seggroups&mode=map&format=image/png" --no-check-certificate

date > /home/denton/mydate
mail -s "DEQ1 drought.sh ran" denton@vt.edu < /home/denton/mydate

echo "4 of 9 deq-drought" >> /media/NAS/deq1daily.log
date >> /media/NAS/deq1daily.log

