#!/bin/sh

#### sudo not allowed inscripts...
### copy all html  dir to deq2
### - except drupal alpha, and beta, and the OM model, 
###   primary for these is on deq2 which pushes here daily
sudo -u rob rsync -aLv /var/www/html/lib/ deq2:/var/www/html/lib/
sudo -u rob rsync -av /var/www/html/om/ deq2:/var/www/html/om/
sudo -u rob rsync -av /var/www/html/d.alpha/ deq2:/var/www/html/d.alpha/
sudo -u rob rsync -av /var/www/html/d.bet/ deq2:/var/www/html/d.bet/

