---
date: "`r format(Sys.time(), '%m/%d/%Y')`"
author: ""
title: "`r params$doc_title`"
output: 
  officedown::rdocx_document:
#  pdf_document:
#    toc: true
#    toc_depth: 2
    mapstyles:
      Normal: ['First Paragraph']
    page_margins:
      bottom: 0.5
      top: 0.5
      right: 1
      left: 0.5
      header: 0.0
      footer: 0.0
params: 
  doc_title: "DEQ/OWS Yield Analysis - [INSERT PROJECT NAME HERE]"
  model_feature: 456224 # Ex: Blue Ridge Shadows = 71977, BIG STONE GAP WTP = 72672: "scenario_6014"
  scenario: "scenario_400"
  model_version: "vahydro-1.0"
  model_pid: FALSE
  image_names: [ "fig.unmet_heatmap_amt", "fig.imp_storage.all", "fig.monthly_demand" ]
  image_descriptions: [ "Unmet Demand", "Storage by Year", "Monthly Demand" ]
  cu_threshold: [-10.0, -20.0, -30.0]
  cu_pre_var: "Qbaseline"
  cu_post_var: "Qout"
  cu_base_runid: FALSE # new method allows a baseline model run
  cu_model: "feature"
  cu_min_valid: 0.1
  cu_decimals: 1
  preferred_runid: FALSE
  table_cols: 1
  include_appendices: c() # options: hydropower, modeling
---
```{r setup, include=FALSE}
# load libraries
library("hydrotools")
#library("openmi.om")
library("jsonlite")
library("knitr")
# load remote code
source("https://raw.githubusercontent.com/HARPgroup/hydro-tools/master/R/rmd_utils.R")
source("https://raw.githubusercontent.com/HARPgroup/hydro-tools/master/VAHydro-2.0/find_name.R")
source("https://raw.githubusercontent.com/HARPgroup/hydro-tools/master/R/om_cu_table.R")
source("https://raw.githubusercontent.com/HARPgroup/hydro-tools/master/R/fac_utils.R")

# set up data source access
basepath='/var/www/R'
source('/var/www/R/config.R')
ds <- RomDataSource$new("http://deq1.bse.vt.edu/d.dh", rest_uname)
ds$get_token(rest_pw)
ds$json_obj_url <- json_obj_url
# select entities and info to display
model_feature <- params$model_feature # the facility or feature to show info/images for
model_pid <- params$model_pid # if the feature has more than one model use this
scenario = params$scenario
scenarios <- c(params$scenario ) # image routine can accomodate multiple
image_names <- params$image_names
model_version <- params$model_version
image_descriptions <- params$image_descriptions
# cu table details all optional, as defaults are set up top
cu_threshold = params$cu_threshold
cu_pre_var = params$cu_pre_var
cu_base_runid = params$cu_base_runid
cu_post_var = params$cu_post_var
cu_model = params$cu_model # The model to use for flows, if empty default to model_feature
cu_min_valid = params$cu_min_valid
cu_decimals = params$cu_decimals
table_cols = params$table_cols
preferred_runid = params$preferred_runid
include_appendices = params$include_appendices

# appendix files
appendix_files = list(
  modeling = "https://raw.githubusercontent.com/HARPgroup/vahydro/master/R/OWS_summaries/appendix_modeling.md",
  hydropower = "https://raw.githubusercontent.com/HARPgroup/vahydro/master/R/OWS_summaries/evaluating_hydropower.md"
)

# load up the models into the data source (they are cached in ds$prop_json_cache)
model_pids = list()
# get the facility model
hid<- model_feature
if (model_pid == FALSE) {
  model_prop <- RomProperty$new(ds,list(featureid=hid, entity_type='dh_feature', propcode=model_version),TRUE)
} else {
  model_prop <- RomProperty$new(ds,list(pid=model_pid),TRUE)
}

# todo: allow multiple features?
model_pids[[1]] = model_prop$pid
cu_model_json = ds$get_json_prop(model_prop$pid)

if (cu_model != 'feature') {
  # we have a different feature for the CU model
  cu_model_prop <- RomProperty$new(ds,list(pid=cu_model),TRUE)
  cu_model_json = ds$get_json_prop(cu_model_prop$pid)
  # note: we do NOT put this into the model_pids list for image display, 
  #       if this should also be image display element use the model_feature only
}
# load the json into cache for later access
itable = om_multi_image_list(ds, model_pids, scenarios, image_names, image_descriptions)
img_table = om_rmd_img_table(itable,table_cols)

# CU table

if (!is.logical(preferred_runid)) {
  scenario <- scenarios[which(scenarios == preferred_runid)]
} else {
  scenario <- scenarios[1] # assumes the first is the chosen (this is not really meant for multi anyhow)
  preferred_runid <- scenario
}

runid <- sub("runid_", "", scenario)
elid <- find_name(cu_model_json,'om_element_connection')$value

if (!is.logical(cu_pre_var)) {
  
  pr_data <- om_get_rundata(elid, runid, omsite, FALSE)
  use_pre_var = cu_pre_var
  # now, if the user has specified a scenario to use as baseline, 
  # get that data, then join it, using the same pre/post column but 
  # joining the baseline column on as Qbaseline 
  use_pre_var = cu_pre_var
  if (!is.logical(cu_base_runid)) {
    base_data <- as.data.frame(om_get_rundata(elid, cu_base_runid, omsite, FALSE))
    pr_data_df <- as.data.frame(pr_data)
    base_msg = "" # a holder in case we have trouble we need to report
    if (nrow(pr_data_df) != nrow(base_data)) {
      base_msg = " Note: Pre and Post data are of different lengths, therefore, comparisons have been made only on overlapping days which may skew the percentile flow values as compared to those that would be calculated from the full time period."
    }
    pr_data_cmp <- sqldf(
      paste0(
        "select a.year, a.month, a.day, a.",cu_post_var,
        ", b.", cu_pre_var, " as Qbaseline ",
        "from pr_data_df as a left outer join base_data as b on ",
        "(a.year = b.year and a.month = b.month and a.day = b.day)",
        "order by a.year, a.month, a.day"
      )
    )
    use_pre_var = "Qbaseline"
    pr_data = pr_data_cmp
  }

  fqcu_table <- om_cu_table(fac_report_info, pr_data, cu_post_var, use_pre_var, cu_threshold, cu_decimals) 
}

```

```{r ModelOverview, echo=FALSE, results = "asis"}
for (i in 1:length(model_pids)) {
  model = ds$prop_json_cache[model_pids[[i]]]
  reports = find_name(model,"reports")
  cat("__Project Overview__\n")
  cat(paste(reports$project_intro$value,"\n\n"))
  cat("__Facility & Intake Model Description__\n")
  cat(paste(reports$model_overview$value,"\n\n"))
  num_scens = length(scenarios)
  preferred_text = ""
  if (num_scens > 0) {
    if (num_scens > 1) {
      scen_num = "scenarios were"
    } else {
      scen_num = "scenario was"
    }
    cat(paste("\n\n__Scenarios:__ ", length(scenarios), "model", scen_num, "simulated to evaluate proposed project impacts:","\n\n"))
    
    for ( i in 1:length(scenarios)) {
      scenario = scenarios[i]
      scenario_info = find_name(model, scenario)
      sname = find_name(scenario_info,"scenario_short_name")
      sintro = find_name(scenario_info, "scenario_intro")
      san = find_name(scenario_info, "scenario_analysis")
      if (scenario == preferred_runid) {
        preferred_text = find_name(scenario_info, "conclusions")
        preferred_name = sname$value
      }
      cat(
        paste(
          paste0("__",sname$value,"__", 
          ":")," ",sintro$value,"  \n\n")
        )
      cat(
        paste(paste0("__Analysis:__"), san$value,"\n\n")
      )
    }
  }
}


if (!is.logical(preferred_runid)) {
  cat(paste0("\n\n__Conclusions__ ",preferred_text$value, "\n\n"))
}

knitr::kable(img_table)
x = length(img_table)

if (!is.logical(cu_pre_var)) {
  cat(paste0("__Table ",x + 1,"__\n", " Consumptive use frequency non-exceedence table for ", preferred_name,"\n\n"))
  fqcu_table$caption_text <- paste("Consumptive use non-exceedence table for", preferred_name)
  fqcu_table
} else {
  cat(paste0("__Table ",x,"__\n", " Consumptive use frequency non-exceedence table for ", preferred_name," not requested.\n\n"))
}
```

```{r Appendix, echo=FALSE, results = "asis"}
cat("### Appendices\n\n\n")
for (i in 1:length(include_appendices)) {
  if (!is.na(appendix_files[include_appendices[i]])) {
    fname = as.character( appendix_files[include_appendices[i]] )
    atext <- paste(readLines(fname), collapse="\n")
    cat(paste(atext, "\n\n"))
  }
}
```