#!/bin/sh

# Create a static version of the map for each day.
cd /var/www/html/drought/state/images/maps
wget -O virginia_drought.png "http://deq1.bse.vt.edu/cgi-bin/mapserv?map=/var/www/html/mapserv/vahydro_drought_status-4-metrics-live.map&layers=usgs_mllr&layers=poli_bounds&layers=proj_seggroups&mode=map&format=image/png" --no-check-certificate