---
date: "`r format(Sys.time(), '%m/%d/%Y')`"
author: ""
title: "`r params$doc_title`"
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
    page_margins:
      bottom: 0.5
      top: 0.5
      right: 1
      left: 0.0
      header: 0.0
      footer: 0.0
params: 
  doc_title: "USGS Gage vs VAHydro Model"
  elid: 251491
  runid: 616
  gageid: '02054530'
---

```{r setup, include=FALSE}
library("dataRetrieval")
library("zoo")
library("hydrotools")

basepath='/var/www/R'
source('/var/www/R/config.R')

elid <- params$elid
runid <- params$runid
gageid <- params$gageid
```


```{r getdata, include=FALSE}
model_flows <- om_get_rundata(elid, runid, site=omsite)
model_flows <- zoo(as.numeric(as.character( model_flows$Qout )), order.by = index(model_flows) );
mstart <- as.Date(min(index(model_flows)))
mend <- as.Date(max(index(model_flows)))

historic <- dataRetrieval::readNWISdv(gageid,'00060')
gage_flows <- zoo(as.numeric(as.character( historic$X_00060_00003 )), order.by = historic$Date);
gage_flows <- window(gage_flows, start = mstart, end = mend)
gstart <- as.Date(min(index(gage_flows)))
gend <- as.Date(max(index(gage_flows)))
model_flows <- window(model_flows, start = gstart, end = gend)

# compare means
# mean(model_flows)
# mean(gage_flows)

# do IHA
model_loflows <- IHA::group2(model_flows)
gage_loflows <- IHA::group2(gage_flows)

title_param <- paste0("\nrunid #",runid)

#l90 data ####################################################### 
model_l90 <- model_loflows["90 Day Min"]
gage_l90 <- gage_loflows["90 Day Min"]
cmp_l90 <- cbind(gage_loflows$year, gage_l90, model_l90)
names(cmp_l90) <- c("Year", "USGS", "Model")
#set ymax to largest value in the 2 data sets, in order to generate plots with consistent axis limits
ymax_val <- max(c(cmp_l90$USGS,cmp_l90$Model))

#l30 data ####################################################### 
model_l30 <- model_loflows["30 Day Min"]
gage_l30 <- gage_loflows["30 Day Min"]
cmp_l30 <- cbind(gage_loflows$year, gage_l30, model_l30)
names(cmp_l30) <- c("Year", "USGS", "Model")

#l7 data ######################################################## 
model_l7 <- model_loflows["7 Day Min"]
gage_l7 <- gage_loflows["7 Day Min"]
cmp_l7 <- cbind(gage_loflows$year, gage_l7, model_l7)
names(cmp_l7) <- c("Year", "USGS", "Model")

#l1 data ######################################################## 
model_l1 <- model_loflows["1 Day Min"]
gage_l1 <- gage_loflows["1 Day Min"]
cmp_l1 <- cbind(gage_loflows$year, gage_l1, model_l1)
names(cmp_l1) <- c("Year", "USGS", "Model")

# turn off scientific notation (makes plot legends look nicer)
options(scipen=999)
```

# Appendix X - Model Calibration Plots:
\newpage

## L90 Model Performance Bar Plot:
```{r l90-plot, fig.width=7, fig.height=4.8, dev='png', echo=FALSE}
barplot(
  cbind(USGS, Model) ~ Year, data=cmp_l90,
  col=c("blue", "black"),
  main=paste("USGS vs VAHydro, 90 Day Low Flow ",title_param,sep=""),
  beside=TRUE,
  ylab = "Streamflow (cfs)",
  ylim = c(0,ymax_val),
  cex.main=0.8,
  cex.axis=0.9,
  cex.lab=1,
  cex.names=0.7
)
legend("topleft",legend=c("USGS", "VAHydro"),fill=c("blue", "black"),cex=1)
```

## L30 Model Performance Bar Plot:
```{r l30-plot, fig.width=7, fig.height=4.8, dev='png', echo=FALSE}
barplot(
  cbind(USGS, Model) ~ Year, data=cmp_l30,
  col=c("blue", "black"),
  main=paste("USGS vs VAHydro, 30 Day Low Flow ",title_param,sep=""),
  beside=TRUE,
  ylab = "Streamflow (cfs)",
  ylim = c(0,ymax_val),
  cex.main=0.8,
  cex.axis=0.9,
  cex.lab=1,
  cex.names=0.7
)
legend("topleft",legend=c("USGS", "VAHydro"),fill=c("blue", "black"),cex=1)
```

## L7 Model Performance Bar Plot:
```{r l7-plot, fig.width=7, fig.height=4.8, dev='png', echo=FALSE}
barplot(
  cbind(USGS, Model) ~ Year, data=cmp_l7,
  col=c("blue", "black"),
  main=paste("USGS vs VAHydro, 7 Day Low Flow ",title_param,sep=""),
  beside=TRUE,
  ylab = "Streamflow (cfs)",
  ylim = c(0,ymax_val),
  cex.main=1,
  cex.axis=0.9,
  cex.lab=1,
  cex.names=0.7
)
legend("topleft",legend=c("USGS", "VAHydro"),fill=c("blue", "black"),cex=1)
```

## L1 Model Performance Bar Plot:
```{r l1-plot, fig.width=7, fig.height=4.8, dev='png', echo=FALSE}
barplot(
  cbind(USGS, Model) ~ Year, data=cmp_l1,
  col=c("blue", "black"),
  main=paste("USGS vs VAHydro, 1 Day Low Flow ",title_param,sep=""),
  beside=TRUE,
  ylab = "Streamflow (cfs)",
  ylim = c(0,ymax_val),
  cex.main=1,
  cex.axis=0.9,
  cex.lab=1,
  cex.names=0.7
)
legend("topleft",legend=c("USGS", "VAHydro"),fill=c("blue", "black"),cex=1)
```


## Model Performance Scatterplots:
```{r l90-errorplots, fig.width=8, fig.height=4.5, dev='png', echo=FALSE}

par(mfrow=c(1,2))

# L90 Scatterplot
m90 <- max(c(max(model_l90$`90 Day Min`), max(gage_l90$`90 Day Min`)))
lm90 <- lm(model_l90$`90 Day Min` ~ gage_l90$`90 Day Min`)
plot(model_l90$`90 Day Min` ~ gage_l90$`90 Day Min`, ylim=c(0,m90), xlim=c(0,m90),
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro, 90 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(lm90,lwd=2,col="blue")
abline(0,1,col="black")
title(ylab="VAHydro 90 Day Low Flow", line=2, cex.lab=0.8)
title(xlab="USGS 90 Day Low Flow", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm90)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm90)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)

# L90 Error Scatterplot
l90_err <- (model_l90$`90 Day Min` - gage_l90$`90 Day Min`)
l90_err_pct <- 100.0 * (model_l90$`90 Day Min` - gage_l90$`90 Day Min`) / gage_l90$`90 Day Min`
lm90_err <- lm(l90_err ~ gage_loflows$year)

plot(l90_err ~ gage_loflows$year,
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro Error, 90 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(reg=lm90_err,lwd=2,col="blue")
abline(0,0,col="black")
title(ylab="90 Day Low Flow Error", line=2, cex.lab=0.8)
title(xlab="Year", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm90_err)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm90_err)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)
```

```{r l30-errorplots, fig.width=8, fig.height=4.5, dev='png', echo=FALSE}

par(mfrow=c(1,2))

# l30 Scatterplot
m30 <- max(c(max(model_l30$`30 Day Min`), max(gage_l30$`30 Day Min`)))
lm30 <- lm(model_l30$`30 Day Min` ~ gage_l30$`30 Day Min`)
plot(model_l30$`30 Day Min` ~ gage_l30$`30 Day Min`, ylim=c(0,m30), xlim=c(0,m30),
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro, 30 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(lm30,lwd=2,col="blue")
abline(0,1,col="black")
title(ylab="VAHydro 30 Day Low Flow", line=2, cex.lab=0.8)
title(xlab="USGS 30 Day Low Flow", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm30)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm30)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)

# l30 Error Scatterplot
l30_err <- (model_l30$`30 Day Min` - gage_l30$`30 Day Min`)
l30_err_pct <- 100.0 * (model_l30$`30 Day Min` - gage_l30$`30 Day Min`) / gage_l30$`30 Day Min`
lm30_err <- lm(l30_err ~ gage_loflows$year)

plot(l30_err ~ gage_loflows$year,
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro Error, 30 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(reg=lm30_err,lwd=2,col="blue")
abline(0,0,col="black")
title(ylab="30 Day Low Flow Error", line=2, cex.lab=0.8)
title(xlab="Year", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm30_err)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm30_err)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)
```

```{r l7-errorplots, fig.width=8, fig.height=4.5, dev='png', echo=FALSE}

par(mfrow=c(1,2))

# l7 Scatterplot
m7 <- max(c(max(model_l7$`7 Day Min`), max(gage_l7$`7 Day Min`)))
lm7 <- lm(model_l7$`7 Day Min` ~ gage_l7$`7 Day Min`)
plot(model_l7$`7 Day Min` ~ gage_l7$`7 Day Min`, ylim=c(0,m7), xlim=c(0,m7),
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro, 7 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(lm7,lwd=2,col="blue")
abline(0,1,col="black")
title(ylab="VAHydro 7 Day Low Flow", line=2, cex.lab=0.8)
title(xlab="USGS 7 Day Low Flow", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm7)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm7)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)

# l7 Error Scatterplot
l7_err <- (model_l7$`7 Day Min` - gage_l7$`7 Day Min`)
l7_err_pct <- 100.0 * (model_l7$`7 Day Min` - gage_l7$`7 Day Min`) / gage_l7$`7 Day Min`
lm7_err <- lm(l7_err ~ gage_loflows$year)

plot(l7_err ~ gage_loflows$year,
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro Error, 7 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(reg=lm7_err,lwd=2,col="blue")
abline(0,0,col="black")
title(ylab="7 Day Low Flow Error", line=2, cex.lab=0.8)
title(xlab="Year", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm7_err)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm7_err)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)
```

```{r l1-errorplots, fig.width=8, fig.height=4.5, dev='png', echo=FALSE}

par(mfrow=c(1,2))

# l1 Scatterplot
m1 <- max(c(max(model_l1$`1 Day Min`), max(gage_l1$`1 Day Min`)))
lm1 <- lm(model_l1$`1 Day Min` ~ gage_l1$`1 Day Min`)
plot(model_l1$`1 Day Min` ~ gage_l1$`1 Day Min`, ylim=c(0,m1), xlim=c(0,m1),
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro, 1 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(lm1,lwd=2,col="blue")
abline(0,1,col="black")
title(ylab="VAHydro 1 Day Low Flow", line=2, cex.lab=0.8)
title(xlab="USGS 1 Day Low Flow", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm1)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm1)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)

# l1 Error Scatterplot
l1_err <- (model_l1$`1 Day Min` - gage_l1$`1 Day Min`)
l1_err_pct <- 100.0 * (model_l1$`1 Day Min` - gage_l1$`1 Day Min`) / gage_l1$`1 Day Min`
lm1_err <- lm(l1_err ~ gage_loflows$year)

plot(l1_err ~ gage_loflows$year,
     cex = 0.8,
     cex.main=0.8,
     cex.axis=0.7,
     cex.lab=0.8,
     col = "blue",
     main=paste("USGS vs VAHydro Error, 1 Day Low Flow ",title_param,sep=""),
     xlab = "",
     ylab = ""
     )
abline(reg=lm1_err,lwd=2,col="blue")
abline(0,0,col="black")
title(ylab="1 Day Low Flow Error", line=2, cex.lab=0.8)
title(xlab="Year", line=2.25, cex.lab=0.8)
legend("topleft",legend=paste("R2: ", format(summary(lm1_err)$r.squared,digits=3),"\n",
                              "p: ", format(summary(lm1_err)$coefficients[2,4],digits=3),"\n",sep=""), cex=0.7)
```