---
date: "`r format(Sys.time(), '%m/%d/%Y')`"
author: ""
title: "`r params$doc_title`"
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
    page_margins:
      bottom: 0.5
      top: 0.5
      right: 1
      left: 0.5
      header: 0.0
      footer: 0.0
params: 
  doc_title: "Model River Segment CIA Summary - [INSERT PROJECT NAME HERE]"
  rseg.hydroids: [67839,68327,68099,68376,68126]
  runid.list: [ "runid_200" ]
  rseg.metric.list: [ "Qout","l30_Qout","l90_Qout","consumptive_use_frac","wd_cumulative_mgd","ps_cumulative_mgd","wd_mgd","ps_mgd" ]
---


```{r setup, include=FALSE}
library(officedown)
library(officer)
library(flextable)
library(hydrotools)
library(rjson)
basepath='/var/www/R'
source('/var/www/R/config.R')
source("https://raw.githubusercontent.com/HARPgroup/hydro-tools/master/VAHydro-2.0/find_name.R") #Used during development
```

```{r UserInputs, include=FALSE}
rseg.hydroids <- params$rseg.hydroid
runid.list <- params$runid.list
rseg.metric.list <- params$rseg.metric.list
```



```{r LoadStatsTableFunction, include=FALSE}
rseg_stats_table <- function (rseg.hydroid,runid.list,rseg.metric.list,site,omsite){
  
  rseg.model <- om_get_model(site, rseg.hydroid)
  rseg_obj_url <- paste(json_obj_url, rseg.model$pid, sep="/")
  rseg_model_info <- om_auth_read(rseg_obj_url, token,  "text/json", "")
  rseg_model_info <- fromJSON(rseg_model_info)
  
  
  rseg_table <- om_model_table(model_info = rseg_model_info,
                               runid.list = runid.list,
                               metric.list = rseg.metric.list,
                               include.elfgen = TRUE,
                               site = site,
                               site_base = omsite
  )
  rseg_table <- cbind(rownames(rseg_table),rseg_table)
  names(rseg_table)[names(rseg_table) == 'rownames(rseg_table)'] <- 'Desc'
  rseg_table_raw <- rseg_table
  
  rseg_table_sql <- paste('SELECT
                    CASE
                      WHEN "Desc" = "model" THEN "River Segment Model Statistics:"
                      WHEN "Desc" = "Qout" THEN "Flow Out (cfs) - (i.e mean flow)"
                      WHEN "Desc" = "Qbaseline" THEN "Flow Baseline (cfs)"
                      WHEN "Desc" = "remaining_days_p0" THEN "Minimum Days of Storage Remaining"
                      WHEN "Desc" = "l30_Qout" THEN "30 Day Low Flow (cfs) (i.e drought flow)"
                      WHEN "Desc" = "l90_Qout" THEN "90 Day Low Flow (cfs) (i.e drought flow)"
                      WHEN "Desc" = "consumptive_use_frac" THEN "Consumptive Use Fraction"
                      WHEN "Desc" = "wd_cumulative_mgd" THEN "Cumulative Withdrawal (MGD)"
                      WHEN "Desc" = "ps_cumulative_mgd" THEN "Cumulative Point Source (MGD)"
                      WHEN "Desc" = "wd_mgd" THEN "Withdrawal (MGD)"
                      WHEN "Desc" = "ps_mgd" THEN "Point Source (MGD)"
                      ELSE Desc
                    END AS Description, *
                   FROM rseg_table_raw
                   WHERE Desc NOT IN ("riverseg","run_date","starttime","endtime","richness_change_abs","richness_change_pct","runid")
                   ',sep='')
  rseg_table <- sqldf(rseg_table_sql)
  rseg_table <- rseg_table[,-2]
  # colnames(rseg_table) <- colnames(fac_table) #Col names need to match before rbind
  #-------------------------------------------------------------------------------
  # statsdf <- rbind(rseg_table,fac_table)
  return(rseg_table)
}
```


```{r LoadRsegStatsTable, include=FALSE}
rseg_table <- data.frame()
#i <- 2
for (i in 1:length(rseg.hydroids)){
  rseg.hydroid <- rseg.hydroids[i]
  rseg_table_i <- rseg_stats_table(rseg.hydroid,runid.list,rseg.metric.list,site,omsite)
  rseg_table <- rbind(rseg_table,rseg_table_i)
}
```


#<!---BLOCK_LANDSCAPE_START--->
### Summary of Results:
```{r RsegStatsTable, echo=FALSE}
ft <- qflextable(rseg_table)

# Set column widths
ft <- width(ft, j = 2:length(rseg_table[1,]), width = 1.9)
ft <- width(ft, j = 1, width = 2.5)

# Add header row -----------------------------------------------------------------------------------
# ft <- add_header_row(x = ft, values = c("", "Scenario Alternatives"),colwidths = c(3, 4))

# Set theme
ft <- theme_box(ft)

# Set background color of select rows --------------------------------------------------------------
ft <- bg(ft, bg = "#EFEFEF", part = "header")
ft <- bg(ft, i = ~ Description == "River Segment Model Statistics:", bg = "#EFEFEF", part = "body")
# ft <- bg(ft, i = ~ Description == "Facility Model Statistics:", bg = "#EFEFEF", part = "body")
fontsize(ft, size = 9)
```
#<!---BLOCK_LANDSCAPE_STOP--->

